// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxJGm3UOq3kKhBfa0ZD3pmn0no1BYtgM',
    appId: '1:873903200845:web:55a9ff04ee2f66bf17da04',
    messagingSenderId: '873903200845',
    projectId: 'project-penulisan-ilmiah-4267a',
    authDomain: 'project-penulisan-ilmiah-4267a.firebaseapp.com',
    storageBucket: 'project-penulisan-ilmiah-4267a.appspot.com',
    measurementId: 'G-5LL4BLN7LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlGuHS4ifVhBxRzNgEnpkLe8eBdxER38',
    appId: '1:873903200845:android:f3c302c58f5b461a17da04',
    messagingSenderId: '873903200845',
    projectId: 'project-penulisan-ilmiah-4267a',
    storageBucket: 'project-penulisan-ilmiah-4267a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvoV-9uFdYlGnb1yab-WIGW76ZjnAsAIw',
    appId: '1:873903200845:ios:8a0c6382e45bbf6517da04',
    messagingSenderId: '873903200845',
    projectId: 'project-penulisan-ilmiah-4267a',
    storageBucket: 'project-penulisan-ilmiah-4267a.appspot.com',
    iosClientId: '873903200845-kaglnsd4u75jomd4n4sfpsmo6j9ss3k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvoV-9uFdYlGnb1yab-WIGW76ZjnAsAIw',
    appId: '1:873903200845:ios:8a0c6382e45bbf6517da04',
    messagingSenderId: '873903200845',
    projectId: 'project-penulisan-ilmiah-4267a',
    storageBucket: 'project-penulisan-ilmiah-4267a.appspot.com',
    iosClientId: '873903200845-kaglnsd4u75jomd4n4sfpsmo6j9ss3k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPi',
  );
}
